=== solzimer/nsyslog/schema/config.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://nsyslog/config.schema.json",
	"type": "object",
	"title": "Monitor Configuration",

	"properties": {
		"config": {
			"$id": "#/properties/config",
			"type": "object",
			"title": "Global Config",
			"properties": {
				"datadir": {
					"type": "string",
					"title": "Monitor data folder. This folder will store watermark, buffer queues and other temporal or persistent monitor data"
				},
				"buffer": {
					"type": "object",
					"title": "Global buffer configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each queue buffer before they are processed"
						}
					}
				},
				"input": {
					"type": "object",
					"title": "Global inputs configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each input buffer before they are processed"
						}
					}
				},
				"processor": {
					"type": "object",
					"title": "Global processors configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each processor buffer before they are processed"
						}
					}
				},
				"transporter": {
					"type": "object",
					"title": "Global transporters configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each transporter buffer before they are processed"
						}
					}
				},
				"auth" : {
					"$ref" : "file:///opt/nsyslog/schema/auth.schema.json"
				}
			}
		},

		"include" : {
			"type" : "array",
			"items" : {
				"type" : "string"
			}
		},

		"inputs" : {
			"$ref" : "file:///opt/nsyslog/schema/inputs.schema.json"
		},

		"processors" : {
			"$ref" : "file:///opt/nsyslog/schema/processors.schema.json"
		},

		"transporters" : {
			"$ref" : "file:///opt/nsyslog/schema/transporters.schema.json"
		},

		"flows" : {
			"$ref" : "file:///opt/nsyslog/schema/flows.schema.json"
		}
	}
}

=== solzimer/nsyslog/examples/config/test049_amqp.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"amqp_test" : {
			"type" : "amqp",
			"config" : {
				"url" : "amqps://ydhsfzhp:57XiJBwJMKnHfCZTpFM0Eu1650USYXII@rat.rmq2.cloudamqp.com/ydhsfzhp",
				"queue" : "test"
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${JSON:0}"
			}
		}
	},

	"flows" : [
		{
			"id":"flow1", 
			"from":"amqp_test",
			"transporters":["console"]
		}
	]
}

=== solzimer/nsyslog/examples/config/test008_windows02.json
{
    "$schema": "file:///opt/nsyslog/schema/config.schema.json",
    "config": {
      "datadir": "/tmp/suitemon",
      "input": {
        "maxPending": 1000
      },
      "buffer": {
        "maxPending": 1000
      },
      "processor": {
        "maxPending": 1000
      },
      "transporter": {
        "maxPending": 1000
      }
    },
    "inputs": {
      "local": {
        "type": "windows",
        "config": {
            "batchsize": 100,
            "channel": "Application",
            "readmode": "watermark",
            "offset" : "start"
        }
      }
    },
    "processors": {
    },
    "transporters": {
      "syslog" : {
          "type": "syslog",
          "config": {
            "application": "TEST",
            "facility" : 1,
            "level" : 3,
            "format": "${JSON}",
            "hostname": "david",
            "url": "tcp://logica5:514"
          }
      },
      "logger": {
        "type": "console",
        "config": {
          "format": "${JSON}"
        }
      },
      "null": {
        "type": "null",
        "config": {}
      }
    },
    "flows": [
      {
        "disabled": false,
        "from": "local",
        "processors": [],
        "transporters": "syslog"
      }
    ]
  }

=== solzimer/nsyslog/examples/config/test051_machine.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100},
		"collector" : {
			"key" : "ctx",
			"ival" : 1000
		}
	},

	"inputs" : {
		"stats" : {
			"type" : "machine",
			"config" : {
			}
		}
	},

	"processors" : {
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"attach" : ["flow1"],
			"config" : {
				"format" : "${JSON:originalMessage.memory}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"stats", "fork":true, "processors":[], "transporters":"console"}
	]
}

=== solzimer/nsyslog/examples/config/test048_retry.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"static_1" : {
			"type" : "static",
			"attach" : ["flow1"],
			"config" : {
				"loop" : true,
				"lines" : [
					"This is a global data"
				]
			}
		}
	},

	"processors" : {
		"props" : {
			"type" : "properties",
			"retry" : {
				"filter" : "${rand}<=0.5",
				"max" : 5,
				"timeout" : 1000
			},
			"config" : {
				"set" : {
					"rand" : "${Math.random()}"
				}
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${JSON:0}"
			}
		}
	},

	"flows" : [
		{
			"id":"flow1", 
			"from":"static_1", 
			"processors":["props"],
			"transporters":["console"]
		}
	]
}

=== solzimer/nsyslog/examples/config/test057_flow_when.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100},
		"collector" : {
			"_key" : "ctx",
			"ival" : 1000
		}
	},

	"inputs" : {
		"lines" : {
			"type" : "static",
			"attach" : ["flow1"],
			"config" : {
				"loop" : true,
				"lines" : [
					{"res":"MAL","ct3":"4688","dun":"user$", "ct5":"algo asi como logagent.exe jejeje"},
					{"res":"BIEN","ct3":"4688","dun":"user$","ct5":"Este tiene que pasar!"}
				]
			}
		}
	},

	"processors" : {
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"attach" : ["flow1"],
			"config" : {
				"format" : "${JSON:2}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{
			"id": "flow1", "from":"lines", 
			"when" : {
				"radek" : {"$or":[{"originalMessage.res" : "MAL"},{"originalMessage.res" : "GOOD"}]}
			},
			"transporters" : ["console"]
		}
	]
}

=== solzimer/nsyslog/examples/config/test055_mongofilter.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100},
		"collector" : {
			"_key" : "ctx",
			"ival" : 1000
		}
	},

	"inputs" : {
		"lines" : {
			"type" : "static",
			"config" : {
				"loop" : true,
				"lines" : [
					{"res":"MAL","ct3":"4688","dun":"user$", "ct5":"algo asi como logagent.exe jejeje"},
					{"res":"BIEN","ct3":"4688","dun":"user$","ct5":"Este tiene que pasar!"}
				]
			}
		}
	},

	"processors" : {
		"event": {
			"type" : "properties",
			"config" : {
				"set" : {
					"evt" : "${originalMessage}"
				}
			}
		},
		"win_discard_user": {
			"type": "properties",
			"config": {},
			"when": {
				"filter": {
					"$and": [
						{"evt.ct3": { "$in": ["4688"] }},
						{"evt.dun": {"$endsWith":["$"]}},		
						{"$expr":{"$eval":"${evt.ct5.indexOf('logagent.exe')} > 0"}}
					]
				},
				"match": "block",
				"nomatch": "bypass"
			}
		}		
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"attach" : ["flow1"],
			"config" : {
				"format" : "${JSON:evt}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{
			"from":"lines", "fork":false, "processors" : ["event","win_discard_user"], "transporters":"console"
		}
	]
}

=== solzimer/nsyslog/examples/config/test043_fwatch.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"lines" : {
			"type" : "file",
			"config" : {

				"path" : "/var/log/apache.log",
				"watch" : true,
				"readmode" : "watermark",
				"offset" : "end",
				"options": {
					"usePolling": true,
					"interval": 100
				}
			}
		}
	},

	"processors" : {},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${originalMessage}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"lines", "fork":false, "processors":[], "transporters":"null"}
	]
}

=== solzimer/nsyslog/examples/config/test056_flowkill.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100},
		"collector" : {
			"_key" : "ctx",
			"ival" : 1000
		}
	},

	"inputs" : {
		"lines" : {
			"type" : "static",
			"attach" : ["myflow"],
			"config" : {
				"loop" : true,
				"interval" : 1000,
				"lines" : [
					{"res":"MAL","ct3":"4688","dun":"user$", "ct5":"algo asi como logagent.exe jejeje"},
					{"res":"BIEN","ct3":"4688","dun":"user$","ct5":"Este tiene que pasar!"}
				]
			}
		}
	},

	"processors" : {
		"event": {
			"type" : "properties",
			"config" : {
				"set" : {
					"evt" : "${originalMessage}"
				}
			}
		},
		"pid": {
			"type" : "properties",
			"config" : {
				"extend" : true,
				"deep" : true,
				"set" : {
					"evt" : {
						"pid" : "${process.pid}"
					}
				}
			}
		},
		"win_discard_user": {
			"type": "properties",
			"config": {},
			"when": {
				"filter": {
					"$and": [
						{"evt.ct3": { "$in": ["4688"] }},
						{"evt.dun": {"$endsWith":["$"]}},		
						{"$expr":{"$eval":"${evt.ct5.indexOf('logagent.exe')} > 0"}}
					]
				},
				"match": "block",
				"nomatch": "bypass"
			}
		}		
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"attach" : ["flow1"],
			"config" : {
				"format" : "${JSON:evt}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{
			"id":"myflow", "from":"lines", "fork":true, "processors" : ["event","pid","win_discard_user"], "transporters":"console"
		}
	]
}
