=== solzimer/nsyslog/schema/config.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://nsyslog/config.schema.json",
	"type": "object",
	"title": "Monitor Configuration",

	"properties": {
		"config": {
			"$id": "#/properties/config",
			"type": "object",
			"title": "Global Config",
			"properties": {
				"datadir": {
					"type": "string",
					"title": "Monitor data folder. This folder will store watermark, buffer queues and other temporal or persistent monitor data"
				},
				"buffer": {
					"type": "object",
					"title": "Global buffer configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each queue buffer before they are processed"
						}
					}
				},
				"input": {
					"type": "object",
					"title": "Global inputs configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each input buffer before they are processed"
						}
					}
				},
				"processor": {
					"type": "object",
					"title": "Global processors configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each processor buffer before they are processed"
						}
					}
				},
				"transporter": {
					"type": "object",
					"title": "Global transporters configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each transporter buffer before they are processed"
						}
					}
				},
				"auth" : {
					"$ref" : "file:///opt/nsyslog/schema/auth.schema.json"
				}
			}
		},

		"include" : {
			"type" : "array",
			"items" : {
				"type" : "string"
			}
		},

		"inputs" : {
			"$ref" : "file:///opt/nsyslog/schema/inputs.schema.json"
		},

		"processors" : {
			"$ref" : "file:///opt/nsyslog/schema/processors.schema.json"
		},

		"transporters" : {
			"$ref" : "file:///opt/nsyslog/schema/transporters.schema.json"
		},

		"flows" : {
			"$ref" : "file:///opt/nsyslog/schema/flows.schema.json"
		}
	}
}

=== solzimer/nsyslog/examples/config/test047_global.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"static_1" : {
			"type" : "static",
			"attach" : ["flow1"],
			"config" : {
				"lines" : [
					"This is a global data"
				]
			}
		},
		"static_2" : {
			"type" : "static",
			"attach" : ["flow2"],
			"config" : {
				"lines" : [
					"null line"
				]
			}
		}
	},

	"processors" : {
		"throttle" : {
			"type" : "throttle",
			"config" : {
				"timeout" : 1000
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "Message from flow1 : ${_.test} / ${_.itop.asamblea.clientId}"
			}
		},
		"global" : {
			"type" : "global",
			"config" : {
				"input" : "${originalMessage}",
				"output" : "test"
			}
		}
	},

	"flows" : [
		{"id":"flow1", "from":"static_1", "fork":true, "transporters":["global"],"mode":"serial"},
		{"id":"flow2", "from":"static_2", "fork":true, "processors":["throttle"], "transporters":["console","#flow2"],"mode":"serial"}
	]
}

=== solzimer/nsyslog/examples/config/test002_kafka_consumer.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"maxPending" : 1000},
		"buffer" : {"maxPending": 1000},
		"processor" : {"maxPending": 1000},
		"transporter" : {"maxPending": 1000}
	},

	"inputs" : {
		"reader_kafka_oracleaudit": {
            "Description": "Attach va de flujo de entrada",
            "attach": [
                "pump_kafka_oracleaudit"
            ],
            "type" : "kafka",
            "disabled" : false,
            "config" : {
                "url" : "kafka://localhost:9090",
                "topics" : [
                    "logline__6299ca1a5ebcd503f5431752", "logline__6299cab65ebcd503f5431953",
                    "logline__6299caf75ebcd503f5431991", "logline__6299cb8f5ebcd503f5431a18"
                ],
                "format" : "json",
                "offset" : "earliest",
                "group" : "monitor_oracleaudit_test",
                "watch" : false
            }
        }
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${this}",
				"json" : {
					"format" : true,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"pump_kafka_oracleaudit", "from":"reader_kafka_oracleaudit", "transporters":["null"]}
	]
}

=== solzimer/nsyslog/examples/config/test054_netfile.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"lines" : {
			"type" : "file",
			"config" : {
				"watch" : true,
				"path" : "/var/log/**/*",
				"readmode" : "watermark",
				"offset" : "end"
			}
		}
	},

	"processors" : {
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${path} - ${ln}"
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"lines", "fork":false, "processors":[], "transporters":"console"}
	]
}

=== solzimer/nsyslog/examples/config/test046_httpsm.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"httpsm" : {
			"type" : "httpsm",
			"config" : {
				"start" : "login",
				"states" : {
					"login" : {
						"options" : {
							"method" : "POST",
							"jar" : true,
							"url" : "https://my.neushield.net/rs/usr/login",
							"headers" : {
								"client_id" : "ndrcloud_webapp_v1"
							},
							"json" : {
								"parameters": {
									"email": "email",
									"password": "password",
									"apiVersion": 4
								}
							}
						},
						"emit" : [
							{
								"when":"${res.statusCode}==200 && ${body.statusCode}==200", 
								"store" : {
									"ticket" : "${body.results.loginData.ticket}",
									"userId" : "${body.data.id}",
									"loginAccountId" : "${body.results.loginData.id}"
								},
								"next":"apilink", 
								"timeout":100, 
								"log":{"level":"info","message":"Neushield auth OK (${body.results.loginData.ticket})"}
							},
							{
								"when":"${res.statusCode}!=200 || ${body.statusCode}!=200", 
								"next":"start", 
								"timeout":5000, 
								"log":{"level":"error","message":"Neushield auth ERROR (${body? this.body.message : this.res.statusCode})"}
							}
						]
					},
					"apilink" : {
						"options" : {
							"method" : "POST",
							"jar" : true,
							"url" : "https://my.neushield.net/rs/oauth/list",
							"headers" : {
								"client_id" : "ndrcloud_webapp_v1"
							},
							"json" : {
								"parameters": {
									"userId": "${userId}",
									"loginAccountId": "${loginAccountId}",
									"loginTicket": "${ticket}",
									"start": 0,
									"max": 5
								}
							}
						},
						"emit" : [
							{
								"when":"${res.statusCode}==200 && ${body.statusCode}==200", 
								"store" : {
									"link" : "${body.results.links.find(l=>l.settings.match(/socservice/))}"
								},
								"next":"authcode",
								"timeout":100, 
								"log":{"level":"info","message":"Neushield api links OK"}
							},
							{
								"when":"${res.statusCode}!=200 || ${body.statusCode}!=200", 
								"next":"start", 
								"timeout":5000, 
								"log":{"level":"error","message":"Neushield api links ERROR (${body? this.body.message : this.res.statusCode})"}
							}
						]
					},
					"authcode" : {
						"debug" : true,
						"options" : {
							"method" : "POST",
							"jar" : true,
							"url" : "https://my.neushield.net/oauth2/v1/token",
							"form" : {
								"grant_type" : "authorization_code",
								"code" : "${link.authCode.value}",
								"client_id" : "${link.clientId}",
								"client_secret" : "${link.value}",
								"redirect_uri" : "https://grupoica.com"
							}
						},
						"emit" : [
							{
								"when":"${res.statusCode}==200", 
								"then": "${body}",
								"store" : {"token":"${body}"},
								"timeout": 1000, 
								"next":"refreshtoken",
								"log":{"level":"info","message":"Neushield grant token OK"}
							},
							{
								"when":"${res.statusCode}!=200", 
								"next":"renewcode", 
								"timeout":100, 
								"log":{"level":"error","message":"Neushield grant token ERROR (${body.error_description}). Will try to renew code"}
							}
						]
					},
					"refreshtoken" : {
						"debug" : true,
						"options" : {
							"method" : "POST",
							"jar" : true,
							"url" : "https://my.neushield.net/oauth2/v1/token",
							"form" : {
								"grant_type" : "refresh_token",
								"refresh_token" : "${token.refresh_token}",
								"client_id" : "${link.clientId}",
								"client_secret" : "${link.value}",
								"redirect_uri" : "https://grupoica.com"
							}
						},
						"emit" : [
							{
								"when":"${res.statusCode}==200", 
								"publish": "${body}",
								"store" : {"token":"${body}"},
								"next" : "refreshtoken",
								"timeout":1000, 
								"log":{"level":"info","message":"Neushield refresh token OK"}
							},
							{
								"when":"${res.statusCode}!=200", 
								"next":"renewcode", 
								"timeout":100, 
								"log":{"level":"error","message":"Neushield refresh token ERROR (${body.error_description}). Will try to renew code"}
							}
						]
					},					
					"renewcode" : {
						"options" : {
							"method" : "POST",
							"jar" : true,
							"url" : "https://my.neushield.net/rs/oauth/request",
							"headers" : {
								"client_id" : "ndrcloud_webapp_v1"
							},
							"json" : {
								"parameters":{
									"userId":"${userId}",
									"loginAccountId":"${loginAccountId}",
									"loginTicket":"${ticket}",
									"linkData":"${link}",
									"type":"code"
								}
							}
						},
						"emit" : [
							{
								"when":"${res.statusCode}==200 && ${body.statusCode}==200", 
								"store" : {
									"link" : "${body.results.apiLink}"
								},
								"next":"authcode",
								"timeout":100, 
								"log":{"level":"info","message":"Neushield renew auth code OK"}
							},
							{
								"when":"${res.statusCode}!=200 || ${body.statusCode}!=200", 
								"next":"start", 
								"timeout":5000, 
								"log":{"level":"error","message":"Neushield renew code ERROR (${body? this.body.message : this.res.statusCode})"}
							}
						]
					}					
				}
			}
		}
	},

	"processors" : {
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${JSON}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"*", "fork":false, "transporters":"console"}
	]
}

=== solzimer/nsyslog/examples/config/test008_windows.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog1",
		"wmdir" : "/tmp/wms1",
		"input" : {"maxPending" : 1000},
		"buffer" : {"maxPending": 1000},
		"processor" : {"maxPending": 1000},
		"transporter" : {"maxPending": 1000}
	},

	"inputs" : {
		"w_1" : {
			"type" : "windows",
			"config" : {
				"readmode" : "offset",
				"offset" : "start",
				"channel" : "Security",
				"batchsize" : 5000,
				"format" : "xml"
			}
		},
		"w_2" : {
			"type" : "windows",
			"config" : {
				"readmode" : "offset",
				"offset" : "start",
				"channel" : "Application",
				"batchsize" : 5000,
				"format" : "xml"
			}
		},
		"w_3" : {
			"type" : "windows",
			"config" : {
				"readmode" : "offset",
				"offset" : "start",
				"channel" : "System",
				"batchsize" : 5000,
				"format" : "xml"
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${originalMessage}",
				"json" : {
					"format" : true,
					"spaces" : 2
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"from":"${type}=='windows'", "fork":false, "transporters":["null"]}
	]
}

=== solzimer/nsyslog/examples/config/test052_regex.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"lines" : {
			"type" : "file",
			"config" : {
				"path" : "/opt/nsyslog/examples/config/data/replaceProblem.txt",
				"readmode" : "offset",
				"offset" : "start"
			}
		}
	},

	"processors" : {
		"replace" : {
			"type" : "properties",
			"config" : {
				"set" : {
					"parsed" : "${originalMessage.replace(/(\\\\\\\\)/g,'\\\\').replace(/(\\\\)r(\\\\)n/g,' ')}"
				}
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${parsed}"
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"lines", "fork":false, "processors":["replace"], "transporters":"console"}
	]
}

=== solzimer/nsyslog/examples/config/test043_datefilewatch.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"lines" : {
			"type" : "file",
			"config" : {
				"path" : "C:\\ica\\data\\logroot\\${DATE:YYYY-MM-DD_mm}\\*.log",
				"watch" : true,
				"readmode" : "watermark",
				"offset" : "start",
				"options": {
					"usePolling": false,
					"interval": 100
				}
			}
		}
	},

	"processors" : {},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${filename} - ${originalMessage}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"lines", "fork":false, "processors":[], "transporters":"console"}
	]
}

=== solzimer/nsyslog/examples/config/test063_split.json
{
  "config": {
    "datadir": "/tmp/nsyslog",
    "frontend": {
      "host": "0.0.0.0",
      "port": 19998,
      "context": "/",
      "ssl": {
        "enabled": false,
        "key": "./monitor.key",
        "cert": "./monitor.crt"
      }
    },
    "input": {
      "buffer": 100
    }
  },
  "inputs": {
    "lines": {
      "type": "static",
      "config": {
        "loop": true,
        "lines": [
          "Evento de auditorÃ­a: audit_schema_version:1\nevent_time:2026-01-05 00:02:11.8630321\nsequence_number:1\\naction_id:BAL \\nsucceeded:true\\nis_column_permission:false\\nsession_id:75\\nserver_principal_id:269\\ndatabase_principal_id:1\\ntarget_server_principal_id:0\\ntarget_database_principal_id:0\\nobject_id:5\\nuser_defined_event_id:0\\ntransaction_id:0\\nclass_type:DB\\nduration_milliseconds:0\\nresponse_rows:0\\naffected_rows:0\\nclient_ip:local machine\\npermission_bitmask:00000000000000000000000000000000\\nsequence_group_id:148947C0-0B80-4923-ABFD-0C783C0DB904\\nsession_server_principal_name:FRINSAadmin_backup\\nserver_principal_name:FRINSAadmin_backup\\nserver_principal_sid:0105000000000005150000001525af47e3a0f57f16c0ea323a1f0000\\ndatabase_principal_name:dbo\\ntarget_server_principal_name:\\ntarget_server_principal_sid:\\ntarget_database_principal_name:\\nserver_instance_name:serv-sql\\ndatabase_name:[DASS_NET]\\nschema_name:\\nobject_name:[DASS_NET]\\nstatement:BACKUP LOG @database_name_var TO DISK = N'F:VeeamBackupSqlLogBackup{389f3740-7a77-4f3f-8de8-52260f1ef064}.bak' WITH NAME='Veeam Backup & Replication', DESCRIPTION='Transaction log backup'\\nadditional_information:\\nuser_defined_information:\\napplication_name:Veeam Backup & Replication\\nconnection_id:0673A6F8-D2C4-486C-8669-5EBA3821567F\\ndata_sensitivity_information:\\nhost_name:SERV-SQL\\n."        ]
      }
    }
  },
  "processors": {
    "parse": {
      "type": "properties",
      "config": {
        "#set" :  {
          "props" : "${message.split('\\n').map(l=>l.split(':')).reduce((m,p)=>(m[p[0]]=p.slice(1).join(':'),m),new Object())}"          
        },
        "set" :  {
          "props" : "${originalMessage.split(String.fromCharCode(10))}"          
        }
      }
    }
  },
  "transporters": {
    "console": {
      "type": "console",
      "config": {
        "format": "${JSON:2}",
        "json": {
          "format": true,
          "spaces": 2,
          "color": true
        }
      }
    },
    "null": {
      "type": "null"
    }
  },
  "flows": [
    {
      "id": "flow1",
      "from": "lines",
      "fork": false,
      "processors": ["parse"],
      "transporters": "console"
    }
  ]
}
