=== solzimer/nsyslog/schema/config.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://nsyslog/config.schema.json",
	"type": "object",
	"title": "Monitor Configuration",

	"properties": {
		"config": {
			"$id": "#/properties/config",
			"type": "object",
			"title": "Global Config",
			"properties": {
				"datadir": {
					"type": "string",
					"title": "Monitor data folder. This folder will store watermark, buffer queues and other temporal or persistent monitor data"
				},
				"buffer": {
					"type": "object",
					"title": "Global buffer configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each queue buffer before they are processed"
						}
					}
				},
				"input": {
					"type": "object",
					"title": "Global inputs configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each input buffer before they are processed"
						}
					}
				},
				"processor": {
					"type": "object",
					"title": "Global processors configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each processor buffer before they are processed"
						}
					}
				},
				"transporter": {
					"type": "object",
					"title": "Global transporters configuration",
					"properties": {
						"maxPending": {
							"type": "integer",
							"title": "Max entries stored in each transporter buffer before they are processed"
						}
					}
				},
				"auth" : {
					"$ref" : "file:///opt/nsyslog/schema/auth.schema.json"
				}
			}
		},

		"include" : {
			"type" : "array",
			"items" : {
				"type" : "string"
			}
		},

		"inputs" : {
			"$ref" : "file:///opt/nsyslog/schema/inputs.schema.json"
		},

		"processors" : {
			"$ref" : "file:///opt/nsyslog/schema/processors.schema.json"
		},

		"transporters" : {
			"$ref" : "file:///opt/nsyslog/schema/transporters.schema.json"
		},

		"flows" : {
			"$ref" : "file:///opt/nsyslog/schema/flows.schema.json"
		}
	}
}

=== solzimer/nsyslog/examples/config/test050_keyval.json
{
	"config" : {
		"datadir" : "/tmp/nsyslog",
		"input" : {"buffer" : 100}
	},

	"inputs" : {
		"lines" : {
			"type" : "static",
			"config" : {
				"loop" : false,
				"lines" : [
					"<22>date=2021-09-23 time=15:44:16.257 device_id=FE200E3A17000421 log_id=0200015528 type=statistics pri=information  session_id=\"18NDPAO7015527-18NDPAO8015527\" client_name=\"\" client_ip=\"10.6.66.201\" client_cc=\"ZZ\" dst_ip=\"10.6.67.2\" from=\"noreply.cav@museodelprado.es\" hfrom=\"noreply.cav@museodelprado.es\" to=\"Enzo.armaroli@gmail.com\" polid=\"7:1:3:museodelprado.es\" domain=\"museodelprado.es\" mailer=\"mta\" resolved=\"FAIL\" src_type=\"int\" direction=\"out\" virus=\"\" disposition=\"Accept\" classifier=\"Not Spam\" message_length=\"1748927\" subject=\"Sus entradas para el Museo del Prado\" message_id=\"6e2e9f20c7374a8fab934dc7bbf36e23@correo01prado.museodelprado.es\" recv_time=\"\" notif_delay=\"0\" scan_time=\"0.081117\" xfer_time=\"1145.342651\" srcfolder=\"\" read_status=\"\""
				]
			}
		}
	},

	"processors" : {
		"syslog" : {
			"type" : "syslogparser",
			"config" : {}
		},
		"parser" : {
			"type" : "keyvalparser",
			"config" : {
				"input" : "${syslog.message.replace(/\\s+/g,' ')}",
				"output" : "out"
			}
		}
	},

	"transporters" : {
		"console" : {
			"type" : "console",
			"config" : {
				"format" : "${JSON}",
				"input" : "${out}",
				"json" : {
					"format" : true,
					"spaces" : 2,
					"color" : true
				}
			}
		},
		"null" : {
			"type" : "null"
		}
	},

	"flows" : [
		{"id":"flow1", "from":"lines", "fork":false, "processors":["syslog","parser"], "transporters":"console"}
	]
}
